version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        VITE_YANDEX_MAPS_API_KEY: ${VITE_YANDEX_MAPS_API_KEY}
    ports:
      - "82:80"
    restart: unless-stopped
    container_name: meshtastic_taubetele_com_82
    environment:
      - NODE_ENV=production
    network_mode: bridge
